// Generated by cargo run -p nexus-core --example export_protocol. Do not edit.
export type HostId = string;
export type AuthenticationMethod = "password" | "privateKey";
export type HostConnectionConfig = { hostname: string, port: number, username: string, authentication: AuthenticationMethod, };
export type Host = { id: HostId, displayName: string, connection: HostConnectionConfig, };
export type HostInput = { id: HostId | null, displayName: string, connection: HostConnectionConfig, };
export type CredentialInput = { password: string | null, privateKey: string | null, passphrase: string | null, };
export type ErrorCode = "validation" | "notFound" | "persistence" | "dns" | "timeout" | "refused" | "authentication" | "unknownHostKey" | "changedHostKey" | "discovery" | "secureStorage" | "cancelled" | "connection" | "conflict" | "policy" | "terminalPty" | "terminalShell" | "terminalUnavailable" | "terminalResize" | "terminalStream" | "terminalStartup" | "terminalChannel";
export type AppError = { code: ErrorCode, message: string, hostKey: HostKeyChallenge | null, };
export type HostKeyChallenge = { hostname: string, port: number, algorithm: string, fingerprint: string, previousFingerprint: string | null, };
export type HostFingerprint = { algorithm: string, sha256: string, };
export type HostIdentity = { hostname: string, fingerprint: HostFingerprint, };
export type HostCapability = { id: string, available: boolean, };
export type ConnectionState = "disconnected" | "connecting" | "awaitingTrust" | "connected" | "disconnecting" | "failed";
export type DiscoverySnapshot = { hostname: string | null, os: string | null, osVersion: string | null, kernel: string | null, architecture: string | null, uptimeSeconds: number | null, loadOne: number | null, memoryTotalBytes: number | null, memoryUsedBytes: number | null, rootTotalBytes: number | null, rootUsedBytes: number | null, observedAt: string, warnings: Array<AppError>, };
export type HostSession = { hostId: HostId, state: ConnectionState, error: AppError | null, identity: HostIdentity | null, capabilities: Array<HostCapability>, discovery: DiscoverySnapshot | null, };
export type HostSessionId = string;
export type TerminalSessionId = string;
export type TerminalSize = { columns: number, rows: number, pixelWidth: number, pixelHeight: number, };
export type TerminalState = "creating" | "open" | "closing" | "closed" | "failed" | "disconnected";
export type TerminalSession = { id: TerminalSessionId, hostId: HostId, hostSessionId: HostSessionId, label: string, state: TerminalState, size: TerminalSize, error: AppError | null, };
export type TerminalOutputBatch = { session: TerminalSession, 
/**
 * Base64 preserves arbitrary PTY bytes across JSON IPC. Chunks remain distinct.
 */
chunksBase64: Array<string>, 
/**
 * True only after the producer has ended and every queued byte has been returned.
 */
outputDrained: boolean, };
export type OperationRisk = "readOnly" | "low" | "moderate" | "high" | "destructive";
export type Operation = { id: string, kind: string, risk: OperationRisk, };
