// Generated by cargo run -p nexus-core --example export_protocol. Do not edit.
export type HostId = string;
export type AuthenticationMethod = "password" | "privateKey";
export type HostConnectionConfig = { hostname: string, port: number, username: string, authentication: AuthenticationMethod, };
export type Host = { id: HostId, displayName: string, connection: HostConnectionConfig, };
export type HostInput = { id: HostId | null, displayName: string, connection: HostConnectionConfig, };
export type CredentialInput = { password: string | null, privateKey: string | null, passphrase: string | null, };
export type ErrorCode = "validation" | "notFound" | "persistence" | "dns" | "timeout" | "refused" | "authentication" | "unknownHostKey" | "changedHostKey" | "discovery" | "secureStorage" | "cancelled" | "connection" | "conflict" | "policy" | "terminalPty" | "terminalShell" | "terminalUnavailable" | "terminalResize" | "terminalStream" | "terminalStartup" | "terminalChannel" | "sftpUnavailable" | "sftpDenied" | "sftpProtocol" | "filePolicy" | "localAccess" | "transfer" | "outcomeUnknown";
export type AppError = { code: ErrorCode, message: string, hostKey: HostKeyChallenge | null, };
export type HostKeyChallenge = { hostname: string, port: number, algorithm: string, fingerprint: string, previousFingerprint: string | null, };
export type HostFingerprint = { algorithm: string, sha256: string, };
export type HostIdentity = { hostname: string, fingerprint: HostFingerprint, };
export type HostCapability = { id: string, available: boolean, };
export type ConnectionState = "disconnected" | "connecting" | "awaitingTrust" | "connected" | "disconnecting" | "failed";
export type DiscoverySnapshot = { hostname: string | null, os: string | null, osVersion: string | null, kernel: string | null, architecture: string | null, uptimeSeconds: number | null, loadOne: number | null, memoryTotalBytes: number | null, memoryUsedBytes: number | null, rootTotalBytes: number | null, rootUsedBytes: number | null, observedAt: string, warnings: Array<AppError>, };
export type HostSession = { hostId: HostId, hostSessionId: HostSessionId | null, state: ConnectionState, error: AppError | null, identity: HostIdentity | null, capabilities: Array<HostCapability>, discovery: DiscoverySnapshot | null, };
export type HostMonitorSample = { hostId: HostId, hostSessionId: HostSessionId, observedAt: string, cpuUsagePercent: number | null, memoryTotalBytes: number | null, memoryUsedBytes: number | null, swapTotalBytes: number | null, swapUsedBytes: number | null, rootTotalBytes: number | null, rootUsedBytes: number | null, networkRxBytesPerSecond: number | null, networkTxBytesPerSecond: number | null, warnings: Array<AppError>, };
export type HostSessionId = string;
export type TerminalSessionId = string;
export type TerminalSize = { columns: number, rows: number, pixelWidth: number, pixelHeight: number, };
export type TerminalState = "creating" | "open" | "closing" | "closed" | "failed" | "disconnected";
export type TerminalSession = { id: TerminalSessionId, hostId: HostId, hostSessionId: HostSessionId, label: string, state: TerminalState, size: TerminalSize, error: AppError | null, };
export type TerminalOutputBatch = { session: TerminalSession, 
/**
 * Base64 preserves arbitrary PTY bytes across JSON IPC. Chunks remain distinct.
 */
chunksBase64: Array<string>, 
/**
 * True only after the producer has ended and every queued byte has been returned.
 */
outputDrained: boolean, };
export type OperationRisk = "readOnly" | "low" | "moderate" | "high" | "destructive";
export type Operation = { id: string, kind: string, risk: OperationRisk, };
export type SftpSessionId = string;
export type LocalGrantId = string;
export type FilePlanId = string;
export type TransferJobId = string;
export type EditorDocumentId = string;
export type TextNewline = "lf" | "crLf";
export type RemoteTextDocument = { id: EditorDocumentId, hostId: HostId, hostSessionId: HostSessionId, sftpSessionId: SftpSessionId, path: string, text: string, originalBytes: number, newline: TextNewline, bom: boolean, maxBytes: number, };
export type SftpExtension = { name: string, version: string, };
export type SftpLimits = { maxPacketBytes: string | null, maxReadBytes: string | null, maxWriteBytes: string | null, maxOpenHandles: string | null, clientChunkBytes: string, listingEntryCap: number, };
export type SftpSessionInfo = { id: SftpSessionId, hostId: HostId, hostSessionId: HostSessionId, protocolVersion: number, extensions: Array<SftpExtension>, limits: SftpLimits, rootPath: string, };
export type RemoteEntryKind = "file" | "directory" | "symlink" | "other" | "unknown";
export type RemoteEntry = { name: string, displayName: string, path: string, kind: RemoteEntryKind, sizeBytes: string | null, modifiedAt: string | null, permissions: string | null, uid: number | null, gid: number | null, };
export type DirectoryListing = { hostId: HostId, hostSessionId: HostSessionId, sftpSessionId: SftpSessionId, path: string, entries: Array<RemoteEntry>, partial: boolean, entryCap: number, };
export type ConflictPolicy = "skip" | "keepBoth" | "replace";
export type LocalGrantKind = "uploadFiles" | "downloadDirectory";
export type LocalSelectionItem = { displayName: string, sizeBytes: string | null, };
export type LocalSelectionGrant = { id: LocalGrantId, kind: LocalGrantKind, items: Array<LocalSelectionItem>, expiresAt: string, };
export type FileOperationKind = "upload" | "download" | "createDirectory" | "rename" | "delete" | "editText";
export type FilePlanItem = { sourceDisplay: string, destinationDisplay: string, sizeBytes: string | null, };
export type FileOperationPlan = { id: FilePlanId, hostId: HostId, hostSessionId: HostSessionId, sftpSessionId: SftpSessionId, kind: FileOperationKind, risk: OperationRisk, conflictPolicy: ConflictPolicy | null, items: Array<FilePlanItem>, expiresAt: string, };
export type TransferDirection = "upload" | "download";
export type TransferState = "queued" | "preparing" | "awaitingDecision" | "transferring" | "cancelRequested" | "finalizing" | "completed" | "failed" | "cancelled" | "outcomeUnknown";
export type TransferJob = { id: TransferJobId, hostId: HostId, hostSessionId: HostSessionId, sftpSessionId: SftpSessionId, direction: TransferDirection, sourceDisplay: string, destinationDisplay: string, state: TransferState, confirmedBytes: string, totalBytes: string | null, error: AppError | null, retryable: boolean, };
