//! Single source of truth: emit IPC declarations or check the checked-in contract.
use nexus_model::*;
use nexus_secrets::CredentialInput;
use ts_rs::{Config, TS};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let config = Config::default();
    let declarations = [
        HostId::decl(&config),
        AuthenticationMethod::decl(&config),
        HostConnectionConfig::decl(&config),
        Host::decl(&config),
        HostInput::decl(&config),
        CredentialInput::decl(&config),
        ErrorCode::decl(&config),
        AppError::decl(&config),
        HostKeyChallenge::decl(&config),
        HostFingerprint::decl(&config),
        HostIdentity::decl(&config),
        HostCapability::decl(&config),
        ConnectionState::decl(&config),
        DiscoverySnapshot::decl(&config),
        HostSession::decl(&config),
        HostSessionId::decl(&config),
        TerminalSessionId::decl(&config),
        TerminalSize::decl(&config),
        TerminalState::decl(&config),
        TerminalSession::decl(&config),
        TerminalOutputBatch::decl(&config),
        OperationRisk::decl(&config),
        Operation::decl(&config),
    ];
    let content = format!(
        "// Generated by cargo run -p nexus-core --example export_protocol. Do not edit.\n{}\n",
        declarations
            .iter()
            .map(|s| format!("export {s}"))
            .collect::<Vec<_>>()
            .join("\n")
    );
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../packages/protocol/src/index.ts");
    if std::env::args().any(|a| a == "--check") {
        if std::fs::read_to_string(path)? != content {
            return Err("Protocol is stale; regenerate it.".into());
        }
    } else {
        std::fs::create_dir_all(path.parent().ok_or("Invalid protocol path")?)?;
        std::fs::write(path, content)?;
    }
    Ok(())
}
